package fall2018.csc207.menu.scoreboard;

import android.content.Context;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.v4.app.Fragment;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;

import java.util.ArrayList;
import java.util.List;

import fall2018.csc207.slidingtiles.R;

/**
 * A fragment representing a list of Items.
 * Class partially generated by Android Studio.
 */
public class ScoreboardListFragment extends Fragment {

    /**
     * Key for use in bundle.
     */
    public static final String SCORES_BUNDLE_KEY = "SCORES";

    /**
     * Mandatory empty constructor for the fragment manager to instantiate the
     * fragment (e.g. upon screen orientation changes).
     */
    public ScoreboardListFragment() {
    }

    /**
     * Called by Android while creating the fragment's view.
     *
     * @param inflater           Used to inflate views in the fragment.
     * @param container          The parent view of the fragment.
     * @param savedInstanceState The previous (saved) state of the fragment.
     * @return The view for the fragment, or null.
     */
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_item_list, container, false);
        List<ScoreboardEntry> scores = new ArrayList<>();
        if (getArguments() != null)
            scores = getArguments().getParcelableArrayList(SCORES_BUNDLE_KEY);

        if (scores != null && scores.size() > 0)
            setupFirstView(view, scores.get(0));

        RecyclerView recyclerView = view.findViewById(R.id.list);
        setupRecyclerView(recyclerView, scores);
        return view;
    }

    /**
     * Setups the RecyclerView (list) of scoreboard entries.
     *
     * @param view   The RecyclerView to populate.
     * @param scores The array of scores to display.
     */
    private void setupRecyclerView(RecyclerView view, List<ScoreboardEntry> scores) {
        Context context = view.getContext();

        view.setLayoutManager(new LinearLayoutManager(context));
        view.setAdapter(new ScoreboardEntryRecyclerViewAdapter(scores));
    }

    /**
     * Setups the view for first place.
     *
     * @param parent   The parent view that contains the first place TextViews.
     * @param topScore The entry containing the top score.
     */
    private void setupFirstView(View parent, ScoreboardEntry topScore) {
        TextView topScoreNameView = parent.findViewById(R.id.topScoreName);
        TextView topScoreNumView = parent.findViewById(R.id.topScoreNum);

        topScoreNameView.setText(topScore.getName());
        topScoreNumView.setText(String.valueOf(topScore.getScore()));
    }
}
